-- MySQL Script generated by MySQL Workbench
-- Sat Jan  5 19:44:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema northwind_dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema northwind_dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `northwind_dw` DEFAULT CHARACTER SET utf8 ;
USE `northwind_dw` ;

-- -----------------------------------------------------
-- Table `northwind_dw`.`Dim_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `northwind_dw`.`Dim_products` (
  `id` INT NOT NULL,
  `categorie` VARCHAR(45) NULL,
  `product_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `northwind_dw`.`Dim_Date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `northwind_dw`.`Dim_Date` (
  `id` INT NOT NULL,
  `year` INT NULL,
  `month` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `northwind_dw`.`Dim_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `northwind_dw`.`Dim_customers` (
  `id` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `northwind_dw`.`Dim_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `northwind_dw`.`Dim_employee` (
  `id` INT NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `salary` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `northwind_dw`.`Fact_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `northwind_dw`.`Fact_orders` (
  `id_products` INT NOT NULL,
  `id_date` INT NULL,
  `id_customers` VARCHAR(45) NULL,
  `id_employees` INT NULL,
  `global_price` FLOAT NULL,
  `quantity` INT NULL,
  INDEX `fk_id_products_idx` (`id_products` ASC) ,
  INDEX `fk_id_date_idx` (`id_date` ASC) ,
  INDEX `fk_id_employee_idx` (`id_employees` ASC) ,
  INDEX `fk_id_customers_idx` (`id_customers` ASC) ,
  CONSTRAINT `fk_id_products`
    FOREIGN KEY (`id_products`)
    REFERENCES `northwind_dw`.`Dim_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_date`
    FOREIGN KEY (`id_date`)
    REFERENCES `northwind_dw`.`Dim_Date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_customers`
    FOREIGN KEY (`id_customers`)
    REFERENCES `northwind_dw`.`Dim_customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_employee`
    FOREIGN KEY (`id_employees`)
    REFERENCES `northwind_dw`.`Dim_employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
